steps:
  # Build da imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--platform=linux/amd64'
      - '-t'
      - 'gcr.io/$PROJECT_ID/feed-alert:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/feed-alert:latest'
      - '.'

  # Push da imagem para Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/feed-alert'

  # Deploy no Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'feed-alert'
      - '--image=gcr.io/$PROJECT_ID/feed-alert:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances=$PROJECT_ID:us-central1:feedalert-db'
      - '--set-env-vars=SPRING_DATASOURCE_URL=jdbc:postgresql:///feedalert_db?cloudSqlInstance=$PROJECT_ID:us-central1:feedalert-db&socketFactory=com.google.cloud.sql.postgres.SocketFactory'
      - '--set-env-vars=SPRING_DATASOURCE_USERNAME=feedback_user'
      - '--set-env-vars=GCLOUD_PROJECT=$PROJECT_ID'
      - '--set-env-vars=SPRING_PROFILES_ACTIVE=prod'
      - '--set-env-vars=APP_NOTIFICATION_MODE=pubsub'
      - '--set-env-vars=SPRING_FLYWAY_ENABLED=false'
      - '--set-env-vars=JWT_SECRET'
      - '--set-secrets=SPRING_DATASOURCE_PASSWORD=db-password:latest'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--timeout=300'

images:
  - 'gcr.io/$PROJECT_ID/feed-alert:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/feed-alert:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'

